---

- name: Update repositories cache and install "nginx" package
  apt:
    name: nginx
    update_cache: yes
  become: yes  
- name: ensure nginx is at the latest version
  apt: name=nginx state=latest
  become: yes
- name: start nginx
  service:
    name: nginx
    state: started
  become: yes
- name: delete static file in sites enabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent     
- name: Copy nginx configuration 
  become: yes
  copy: 
    src : templates/default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx