---
- name: Install MySQL
  apt:
    pkg:
    - mysql-server
    - python3-pymysql
    - python-mysqldb
  become: yes
# MySQL Configuration
- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true 
  become: yes
- name: update mysql root password for all root accounts
  become: yes
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: Root@123
    login_user: root
    login_password: Root@123
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - 127.0.0.1
    - 10.0.0.11
    - 10.0.0.12
    - 10.0.0.13
    - ::1
    - localhost   
- name: Copy SQL config file
  become: yes
  copy:
    src: files/my.cnf
    dest: /etc/mysql/my.cnf
    mode: 755
  notify: restart mysql   