---

- name: install JDK 11
  apt:
    name: openjdk-11-jdk
    state: present
  become: yes  

- name: add tomcat group
  group:
    name: tomcat
  become: yes  

- name: add tomcat user
  user:
    name: tomcat
    group: tomcat
    home: /user/share/tomcat
    createhome: no
    system: yes
  become: yes  

- name: create /opt/tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    mode: 0755

- name: download & unarchive
  unarchive:
    src: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.30/bin/apache-tomcat-9.0.30.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: yes  

- name: Change ownership
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory
  become: yes  

- name: Copy Tomcat service from local to remote
  become: yes 
  copy:
    src: templates/tomcat.service
    dest: /etc/systemd/system/
  when: ansible_service_mgr == "systemd"
   

- name: Start and enable tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"  
